- hosts: localhost
  name: Setup Web Server
  become: yes
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
    - name: Installing Nginx
      yum:
        name: nginx
        state: latest
    - name: Restarting Nginx
      service:
        name: nginx
        state: restarted
